### ISSUE TITLE
loged in and attempted to create fursona profile

### ISSUE THREAD

**Issue by davids-tips** [MyFursona-Project/MyFursona#22]
Attempted to create profile but name is undefined#undefined and cannot change it...
![Screenshot (6)](https://user-images.githubusercontent.com/70023798/179334922-2b9c9c45-9c11-499c-9f76-0c7be65c212a.png)

**Comment by VulpoTheDev** [comment]
Hello There! Thanks for taking a look around. Currently we're working on the backend ready and we plan to rework the login system and mostly a lot once the backend gets completed :3

**Comment by davids-tips** [comment]
Ah I will follow this repo to see updates ^w^.
