### ISSUE TITLE
The github icon is not displayed as clickable

### ISSUE THREAD

**Issue by eoan-ermine** [MyFursona-Project/MyFursona#26]
![chrome_y5iwDLa0NH](https://user-images.githubusercontent.com/47888628/209244696-1d48d1f2-72a7-43e2-9b41-a2d6455a9a6f.png)

**Comment by VulpoTheDev** [comment]
Hewwo there! Thank you for creating this issue and bringing it to our attention. We plan to rewrite this in Nuxt along with remaking the Backend and within the next rewrite we plan to fix any styling issues going on like that
