### ISSUE TITLE
BUG: Add the tittle

### ISSUE THREAD

**Issue by ulf-frostypaw** [MyFursona-Project/MyFursona#28]
fix the bug of all pages. .w.

**Comment by kuroji-fusky** [comment]
Oh, sorry about that! We're reworking the entire infrastructure of this project from the ground up earlier this year. Currently, we're rewriting the whole site in Nuxt 3 and we understand that the current website at the moment still needs work.

Please understand that we're just a small team of passionate devs partially working on and off of MyFursona, so be patient!
